openapi: 3.0.0
info:
  title: Subdomain finder
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /:
    get:
      summary: Get all domain names
      operationId: getAll
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /find-subdomains:
    parameters:
      - in: query
        name: domain
        required: true
        schema:
          type: string
          description: Domain to be searched
      - in: query
        name: maxTrials
        schema:
          type: integer
          description: Maximum number of subdomains to try. Tries all if not specified
      - in: query
        name: searchRandom
        schema:
          type: boolean
          default: false
          description: Whether to search subdomains in random order
      - in: query
        name: method
        required: true
        schema:
          type: string
          description: Search method to use
          enum:
            - active
            - passive
    get:
      summary: Find subdomains
      operationId: findSubdomains
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  subdomains:
                    type: array
                    items:
                      type: string
        400:
          description: Bad request if domain or method is not specified
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
